name: Create Release and Upload ZIP

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create ZIP archive from dist
        run: |
          cd dist
          zip -r ../release-${{ github.ref }}.zip .

      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v4
        with:
          title: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-${{ github.ref }}.zip
