name: Create Release and Upload ZIP

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
  workflow_run:
    workflows: ["Create Version Tag"]
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Get the tag name
        id: get_tag
        run: |
          if [[ ${{ github.ref_name }} ]]; then
            VERSION="$(cat package.json | jq -r '.version')"
            if [[ *"alpha"* == $VERSION]]; then
              echo "alpha"
              echo "tag=alpha" >> $GITHUB_OUTPUT
            elif [[ *"beta"* == $VERSION]]; then
              echo "beta"
              echo "tag=beta" >> $GITHUB_OUTPUT
            else
              echo "latest"
              echo "tag=latest" >> $GITHUB_OUTPUT
            fi
          else
            echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT 
          fi

      - name: Create ZIP archive from dist
        run: |
          echo ${{ steps.get_tag.outputs.tag }}
          cd dist
          zip -r ../tldraw-ext-${{ steps.get_tag.outputs.tag }}.zip .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_tag.outputs.tag }}
          name: TLDraw EXT ${{ steps.get_tag.outputs.tag }}
          artifacts: "tldraw-ext-${{ steps.get_tag.outputs.tag }}.zip"
          artifactContentType: "application/zip"
          prerelease: ${{ contains(steps.get_tag.outputs.tag, 'alpha') || contains(steps.get_tag.outputs.tag, 'beta') }}
