name: Create Release and Upload ZIP

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create ZIP archive from dist
        run: |
          cd dist
          zip -r ../release-${{ github.ref_name }}.zip .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          artifacts: "release-${{ github.ref_name }}.zip"
          artifactContentType: "application/zip"
          prerelease: true
