name: Create Release and Upload ZIP

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - main
    paths:
      - package.json

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Get the tag name
        id: get_tag
        run: |
          PKG_VERSION="v$(jq -r '.version' package.json)"
          # echo "tag=v$(${{ github.ref_name }} || $PKG_VERSION)" >> $GITHUB_OUTPUT
          echo "${{ github.ref_name }}"
          echo "$PKG_VERSION"
          echo "${${{ github.ref_name }}:-$PKG_VERSION}"

          # if [[ ${{ github.ref }} == "refs/tag/*" ]]; then
          #   echo "tag=v${{ github.ref_name }}" >> $GITHUB_OUTPUT
          # else
          #   echo "tag=v$PKG_VERSION" >> $GITHUB_OUTPUT

          #   if [[ $VERSION == *"alpha"* ]]; then
          #     echo "update=alpha" >> $GITHUB_OUTPUT
          #   elif [[ $VERSION == *"beta"* ]]; then
          #     echo "update=beta" >> $GITHUB_OUTPUT
          #   else
          #     echo "update=latest" >> $GITHUB_OUTPUT
          #   fi
          # fi

      - name: Create ZIP archive from dist
        run: |
          echo ${{ steps.get_tag.outputs.tag }}
          cd dist
          zip -r ../tldraw-ext-${{ steps.get_tag.outputs.tag }}.zip .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_tag.outputs.tag }}
          name: TLDraw EXT ${{ steps.get_tag.outputs.tag }}
          artifacts: "tldraw-ext-${{ steps.get_tag.outputs.tag }}.zip"
          artifactContentType: "application/zip"
          prerelease: ${{ contains(steps.get_tag.outputs.tag, 'alpha') || contains(steps.get_tag.outputs.tag, 'beta') }}
