name: Create Release and Upload ZIP

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
  workflow_run:
    workflows: ["Create Version Tag"]
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Create ZIP archive from dist
        run: |
          cd dist
          zip -r ../tldraw-ext-${{ github.ref_name }}.zip .

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: TLDraw EXT ${{ github.ref_name }}
          artifacts: "tldraw-ext-${{ github.ref_name }}.zip"
          artifactContentType: "application/zip"
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
