name: Create Version Tag

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: bogdanbpeterson/action-tag-npm@master
      # - name: Create a release
      #   run: |
      #     gh workflow run release.yml
