name: Create Version Tag

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: neverendingqs/gh-action-tag-on-npm-version@master
        with:
          git-user-email: github@bogdanbpeterson.com
          git-user-name: Bogdan B Peterson
