name: Create Version Tag

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bogdanbpeterson/action-tag-npm@v1.0.0
        with:
          gh-email: "github-actions@users.noreply.github.com"
          gh-user: "GitHub Actions"
