name: Create Version Tag

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: bogdanbpeterson/action-tag-npm@v1.0.0
        with:
          git-user-email: "github@bogdanbpeterson.com"
          git-user-name: "Bogdan B Peterson"
